### PR TITLE
Update Emulator to Use SDL2 & TTF Fonts

### LINKED ISSUE #20: Support newer SDL releases
Currently, this is all built around and requires SDL 1.2. Its an old release and bumping up to the latest might afford some better features in SDL. Dunno.

### PR DESCRIPTION
**Pull request by CaptainNic**
## Background
Resolves #20.

## Changes
 * Update emulator from `SDL1.2` to `SDL2`
 * Use `SDL2_TTF` for TrueType Font support, replaces CGA font rendering functions
 * Add `kongtext` font ([source](https://www.dafont.com/kongtext.font))
 * Clean up UI API a bit (now that I look at the diff, I guess I rewrote it :man_shrugging: )
 * Update `makefile`: now creates a `build` dir in project root which includes `msemu` and the font dir. Emulator expects to be run out of the `build` dir, or else the font file can't be found.

### CODE REVIEW

**Comment by kbembedded** [comment]
Initial problems with testing:
- "src/makefile" changes were reverted
- `msemu` has to be run from the src/ directory (or from build/) due to font. Is there a clean way to build the font in to the final binary?
- `make clean` from inside src/ directory attempts to remove /fonts (does the right then when `make clean` is run from toplevel directory)
- `make` from inside src/ directory tries to create /msemu (does the right then when run from toplevel)

**Comment by kbembedded** [comment]
Rebased to current master, cleaned up a couple of things on top of that. Take a look and see what you think.

**Comment by CaptainNic** [comment]
@kbembedded your changes look good. Need to setup my env again to actually test it...

**Comment by CaptainNic** [comment]
With the power bestowed upon me by @kbembedded, I am pressing the merge button with his permission: 
> press it

**Pull request merged**
